server {
         listen 80;
         listen [::]:80;
         root /home/ulocker/ui;
         index index.html index.htm;
         server_name localhost;
         location / {
              try_files $uri /index.html;
         }
}